/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.hospitalmanagement;

import Objects.Patient;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author numan.kilincoglu
 */
public class AdminUpdatePatient extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    int id;

    /**
     * Creates new form BashekimUpdatePatient
     */
    public AdminUpdatePatient() {
        initComponents();
        lbl_tcWarn.setVisible(false);
        lbl_nameWarning.setVisible(false);
        lbl_warn.setVisible(true);
        fillBlanks();
    }

    public AdminUpdatePatient(int id) {
        initComponents();
        this.id = id;
        lbl_tcWarn.setVisible(false);
        lbl_nameWarning.setVisible(false);
        lbl_warn.setVisible(true);
        fillBlanks();
    }

    /**
     * private javax.swing.JTextArea adress_txt;
     *
     * private com.toedter.calendar.JDateChooser datechooser; This method is
     * called from within the constructor to initialize the form. WARNING: Do
     * NOT modify this code. The content of this method is always regenerated by
     * the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnl_udatePatient = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        surname_txt = new javax.swing.JTextField();
        txt_mail = new javax.swing.JTextField();
        g_male = new javax.swing.JRadioButton();
        g_female = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pass_txt = new javax.swing.JPasswordField();
        combo_city = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adress_txt = new javax.swing.JTextArea();
        datechooser = new com.toedter.calendar.JDateChooser();
        update_btn = new javax.swing.JButton();
        phone_txt = new javax.swing.JFormattedTextField();
        blood_group = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txt_tcno = new javax.swing.JFormattedTextField();
        pass_bar = new javax.swing.JProgressBar();
        lbl_nameWarning = new javax.swing.JLabel();
        lbl_tcWarn = new javax.swing.JLabel();
        lbl_warn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pnl_udatePatient.setBackground(new java.awt.Color(170, 255, 255));
        pnl_udatePatient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_udatePatient.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("NAME:");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("SURNAME:");

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("TC NO");

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("PHONE");

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("MAIL");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("GENDER:");

        name_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        surname_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        surname_txt.setForeground(new java.awt.Color(0, 0, 0));

        txt_mail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_mail.setForeground(new java.awt.Color(0, 0, 0));

        buttonGroup1.add(g_male);
        g_male.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        g_male.setForeground(new java.awt.Color(0, 0, 0));
        g_male.setText("MALE");

        buttonGroup1.add(g_female);
        g_female.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        g_female.setForeground(new java.awt.Color(0, 0, 0));
        g_female.setText("FEMALE");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("PASSWORD:");

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("ADRESS:");

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("PLACE OF BIRTH:");

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("DATE OF BIRTH");

        pass_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pass_txt.setForeground(new java.awt.Color(0, 0, 0));
        pass_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pass_txtKeyReleased(evt);
            }
        });

        combo_city.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo_city.setForeground(new java.awt.Color(0, 0, 0));
        combo_city.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DUZCE", "ISTANBUL", "ANKARA", "IZMIR", "ADANA", "KOCAELI" }));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Update Patient Informations");

        adress_txt.setColumns(20);
        adress_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adress_txt.setForeground(new java.awt.Color(0, 0, 0));
        adress_txt.setLineWrap(true);
        adress_txt.setRows(5);
        adress_txt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(adress_txt);

        datechooser.setForeground(new java.awt.Color(0, 0, 0));
        datechooser.setToolTipText("");

        update_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        update_btn.setForeground(new java.awt.Color(0, 0, 0));
        update_btn.setText("UPDATE");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        phone_txt.setForeground(new java.awt.Color(0, 0, 0));
        try {
            phone_txt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("0##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        phone_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        blood_group.setForeground(new java.awt.Color(0, 0, 0));
        blood_group.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "B+", "AB+", "0+", "A-", "B-", "AB-", "0-" }));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("BLOOD GROUP:");

        txt_tcno.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txt_tcno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_tcno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lbl_nameWarning.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbl_nameWarning.setForeground(new java.awt.Color(255, 0, 51));
        lbl_nameWarning.setText("* Name, Surname must contain only letters.");

        lbl_tcWarn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbl_tcWarn.setForeground(new java.awt.Color(255, 0, 51));
        lbl_tcWarn.setText("* TCNO,mail and phone must be unique.");

        lbl_warn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbl_warn.setForeground(new java.awt.Color(255, 0, 0));
        lbl_warn.setText("* Please fill in all the required fields.");

        javax.swing.GroupLayout pnl_udatePatientLayout = new javax.swing.GroupLayout(pnl_udatePatient);
        pnl_udatePatient.setLayout(pnl_udatePatientLayout);
        pnl_udatePatientLayout.setHorizontalGroup(
            pnl_udatePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_udatePatientLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(270, 270, 270))
            .addGroup(pnl_udatePatientLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(pnl_udatePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(update_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_udatePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pnl_udatePatientLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_udatePatientLayout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_udatePatientLayout.createSequentialGroup()
                            .addGroup(pnl_udatePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                            .addGroup(pnl_udatePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(phone_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_tcno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(surname_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnl_udatePatientLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datechooser, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(pnl_udatePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_udatePatientLayout.createSequentialGroup()
                        .addGroup(pnl_udatePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(48, 48, 48)
                        .addGroup(pnl_udatePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pass_bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combo_city, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pass_txt)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addGroup(pnl_udatePatientLayout.createSequentialGroup()
                                .addGroup(pnl_udatePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(g_male, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(blood_group, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(25, 25, 25)
                                .addComponent(g_female, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnl_udatePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_nameWarning, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_warn, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_tcWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        pnl_udatePatientLayout.setVerticalGroup(
            pnl_udatePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_udatePatientLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(pnl_udatePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(pnl_udatePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pass_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pass_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(pnl_udatePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_udatePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(surname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addGroup(pnl_udatePatientLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(pnl_udatePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_udatePatientLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(42, 42, 42)
                                .addGroup(pnl_udatePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txt_tcno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(pnl_udatePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_udatePatientLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(pnl_udatePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(phone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addGroup(pnl_udatePatientLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(combo_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnl_udatePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_udatePatientLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(pnl_udatePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(blood_group, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_udatePatientLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(43, 43, 43)))
                .addGroup(pnl_udatePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_udatePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(g_male)
                        .addComponent(g_female))
                    .addComponent(datechooser, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(pnl_udatePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_udatePatientLayout.createSequentialGroup()
                        .addComponent(update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl_udatePatientLayout.createSequentialGroup()
                        .addComponent(lbl_nameWarning)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_tcWarn)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_warn)
                        .addContainerGap(26, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_udatePatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_udatePatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        getInfo();
    }//GEN-LAST:event_update_btnActionPerformed

    //password strentgh test
    private void pass_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass_txtKeyReleased
        pass_bar.setForeground(Color.BLACK);
        String pass = new String(pass_txt.getPassword());
        pass_bar.setStringPainted(true);
        int strength = passwordStrength(pass);
        pass_bar.setValue(strength * 10);
    }//GEN-LAST:event_pass_txtKeyReleased

    public int passwordStrength(String pass) {

        int passwordStrength = 0;
        if (pass.length() < 5) {
            return 0;
        } else if (pass.length() >= 10) {
            passwordStrength += 2;
        } else {
            passwordStrength += 1;
        }

        if (pass.matches("(?=.*[0-9]).*")) {
            passwordStrength += 2;
        }

        if (pass.matches("(?=.*[a-z]).*")) {
            passwordStrength += 2;
        }

        if (pass.matches("(?=.*[A-Z]).*")) {
            passwordStrength += 2;
        }

        if (pass.matches("(?=.*[~!@#$%^&*()_-]).*")) {
            passwordStrength += 2;
        }
        return passwordStrength;
    }
    //this method fetches selected patient's informations from database.

    public void fillBlanks() {

        try {
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/HastaneYonetimSistemi", "sa", "as");
            String query = ("SELECT * FROM PATIENTS WHERE ID = ?");
            pst = conn.prepareStatement(query);
            pst.setInt(1, this.id);
            rs = pst.executeQuery();
            if (rs.next()) {
                name_txt.setText(rs.getString("NAME"));
                surname_txt.setText(rs.getString("SURNAME"));
                txt_tcno.setText(rs.getString("TCNO"));
                phone_txt.setText(rs.getString("PHONE"));
                txt_mail.setText(rs.getString("MAIL"));
                pass_txt.setText(rs.getString("PASSWORD"));
                adress_txt.setText(rs.getString("ADRESS"));
                conn.close();

            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminUpdatePatient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    //THIS METHOD TAKES INFORMATIONS FROM TEXTFIELDS.
    public void getInfo() {

        boolean rval = false;
        Connection conn = null;
        String pass = new String(pass_txt.getPassword());
        SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");
        String hastaTC = txt_tcno.getText();
        String name = name_txt.getText();
        String surname = surname_txt.getText();
        String phone = phone_txt.getText();
        String mail = txt_mail.getText();
        String city = (String) combo_city.getSelectedItem();

        //regex control
        Matcher matcher;

        if (txt_tcno.getText().isEmpty()) {
            lbl_tcWarn.setVisible(true);
            return;
        } else {
            lbl_tcWarn.setVisible(false);
        }

        if (name_txt.getText().isEmpty()) {
            lbl_nameWarning.setVisible(true);
            return;
        } else {
            matcher = Pattern.compile("^[a-zA-Z\\u0080-\\u9fff]*+$").matcher(name_txt.getText());
            if (!matcher.find()) {
                System.out.println("tutamdi");
                lbl_nameWarning.setVisible(true);
                return;
            } else {
                System.out.println("tutttu");
                lbl_nameWarning.setVisible(false);
            }
        }

        if (surname_txt.getText().isEmpty()) {
            lbl_nameWarning.setVisible(true);
            return;
        } else {
            matcher = Pattern.compile("^[a-zA-Z\\u0080-\\u9fff]*+$").matcher(surname_txt.getText());
            if (!matcher.find()) {
                System.out.println("tutamdi");
                lbl_nameWarning.setVisible(true);
                return;
            } else {
                System.out.println("tutttu");
                lbl_nameWarning.setVisible(false);
            }
        }

        if (phone_txt.getText().length() != 11) {
            lbl_tcWarn.setVisible(true);
            return;
        } else {
            lbl_tcWarn.setVisible(false);
        }

        if (txt_mail.getText().isEmpty()) {
            lbl_tcWarn.setVisible(true);
            return;
        } else {
            matcher = Pattern.compile("^[a-zA-Z][\\w\\d]{2,}@[a-z]{2,10}(.com)$").matcher(txt_mail.getText());
            if (!matcher.find()) {
                lbl_tcWarn.setVisible(true);
                return;
            } else {
                lbl_tcWarn.setVisible(false);
            }
        }

        if (pass_txt.getPassword().length == 0) {
            lbl_warn.setVisible(true);
            return;
        } else {
            if (pass_bar.getValue() < 33) {
                lbl_warn.setVisible(true);
                return;
            } else {
                lbl_warn.setVisible(false);
            }
        }

        if (datechooser.getDate() == null) {
            lbl_warn.setVisible(true);
            return;
        } else {
            lbl_warn.setVisible(false);
        }

        if (buttonGroup1.getSelection() == null) {
            lbl_warn.setVisible(true);
            return;

        }

        System.out.println("buraya geldi----");

        String datebirth = date.format(datechooser.getDate());

        String gender = "";
        if (g_male.isSelected()) {
            gender = "MALE";
        } else {
            gender = "FEMALE";
        }
        boolean control = updateRecords(hastaTC, pass, name, surname, phone, mail, city, datebirth, gender);

        if (control) {
            JOptionPane.showMessageDialog(rootPane, "Record Uptated", "Successfull", JOptionPane.INFORMATION_MESSAGE);
            int x = JOptionPane.showConfirmDialog(rootPane, "Do you want to go main page", "Information", JOptionPane.YES_NO_OPTION);
            if (x == JOptionPane.YES_OPTION) {
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "TCNO, PHONE AND MAIL MUST BE UNIQUE!", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }

    }

    //this method updates patient'S records.        
    public boolean updateRecords(String tc, String pass, String name, String surname, String phone, String mail, String city, String datebirth, String gender) {
        boolean rvalue = false;
        try {
            //checks if these are unique or not in database.
            boolean x = mailControl(mail, tc);
            boolean y = phoneControl(phone, tc);
            boolean z = tcControl(tc);
            if (!z) {
                if (!x) {
                    if (!y) {
                        //if they are unique, this statement update patient records.
                        conn = DriverManager.getConnection("jdbc:derby://localhost:1527/HastaneYonetimSistemi", "sa", "as");
                        pst = conn.prepareStatement("UPDATE PATIENTS SET NAME = ?, SURNAME = ?, PHONE=? , MAIL=?, PLACEBIRTH =?, BIRTHDATE=? , GENDER=?, TCNO = ?, PASSWORD=? WHERE ID = ?");
                        pst.setString(1, name);
                        pst.setString(2, surname);
                        pst.setString(3, phone);
                        pst.setString(4, mail);
                        pst.setString(5, city);
                        pst.setString(6, datebirth);
                        pst.setString(7, gender);
                        pst.setString(8, tc);
                        pst.setString(9, pass);
                        pst.setInt(10, this.id);
                        pst.executeUpdate();
                        conn.close();
                        rvalue = true;
                        return rvalue;
                    }
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(AdminUpdatePatient.class.getName()).log(Level.SEVERE, null, ex);
        }
        return rvalue;

    }

    //following 3 methods control uniqueness of mail,tc,and phone.
    public boolean mailControl(String mail, String tc) {

        boolean rvalue = false;
        try {
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/HastaneYonetimSistemi", "sa", "as");
            pst = conn.prepareStatement("SELECT * FROM PATIENTS WHERE MAIL = ?");
            pst.setString(1, mail);
            rs = pst.executeQuery();
            int key = 0;
            String TC = "";
            while (rs.next()) {
                TC = rs.getString("TCNO");
                key++;
            }
            conn.close();
            if (key > 2) {
                rvalue = true;
                System.out.println("key > 2 girdi");
            } else if (key > 1 && !TC.equals(tc)) {
                rvalue = true;
                System.out.println("key > 1 girdi");
            } else if (key == 1 && !TC.equals(tc)) {
                System.out.println("key == 1 ve !tc girdi");
                rvalue = true;
            } else if (key == 1 && TC.equals(tc)) {
                System.out.println("key ==1 girdi");
                rvalue = false;

            }

            System.out.println("mail count " + key);
        } catch (SQLException ex) {
            Logger.getLogger(AdminUpdatePatient.class.getName()).log(Level.SEVERE, null, ex);
        }
        return rvalue;

    }

    public boolean phoneControl(String number, String tc) {
        boolean rvalue = false;
        try {

            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/HastaneYonetimSistemi", "sa", "as");
            pst = conn.prepareStatement("SELECT * FROM PATIENTS WHERE PHONE = ?");
            pst.setString(1, number);
            rs = pst.executeQuery();
            int key = 0;
            String TC = "";
            while (rs.next()) {
                System.out.println(rs.getString("NAME"));
                TC = rs.getString("TCNO");
                key++;
            }
            conn.close();
            if (key > 2) {
                System.out.println("key > 2 girdi");
                rvalue = true;
            } else if (key > 1 && !TC.equals(tc)) {
                System.out.println("key > 1 girdi");
                rvalue = true;
            } else if (key == 1 && !TC.equals(tc)) {
                System.out.println("key == 1 ve !tc gird");
                rvalue = true;
            } else if (key == 1 && TC.equals(tc)) {
                System.out.println("key ==1 girdi");
                rvalue = false;
            }
            System.out.println("tel count " + key);
        } catch (SQLException ex) {
            Logger.getLogger(AdminUpdatePatient.class.getName()).log(Level.SEVERE, null, ex);
        }

        return rvalue;

    }

    public boolean tcControl(String tc) {

        boolean rvalue = false;
        try {

            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/HastaneYonetimSistemi", "sa", "as");
            pst = conn.prepareStatement("SELECT * FROM DOCTORS WHERE TCNO = ?");
            pst.setString(1, tc);
            rs = pst.executeQuery();
            int key = 0;
            String TC = "";
            while (rs.next()) {
                System.out.println(rs.getString("NAME"));
                TC = rs.getString("TCNO");
                key++;
            }
            conn.close();
            if (key > 2) {
                System.out.println("key > 2 girdi");
                rvalue = true;
            } else if (key > 1 && !TC.equals(tc)) {
                System.out.println("key > 1 girdi");
                rvalue = true;
            } else if (key == 1 && !TC.equals(tc)) {
                System.out.println("key == 1 ve !tc gird");
                rvalue = true;
            } else if (key == 1 && TC.equals(tc)) {
                System.out.println("key ==1 girdi");
                rvalue = false;
            }
            System.out.println("tel count " + key);
        } catch (SQLException ex) {
            Logger.getLogger(AdminUpdatePatient.class.getName()).log(Level.SEVERE, null, ex);
        }

        return rvalue;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUpdatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUpdatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUpdatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUpdatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUpdatePatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea adress_txt;
    private javax.swing.JComboBox<String> blood_group;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combo_city;
    private com.toedter.calendar.JDateChooser datechooser;
    private javax.swing.JRadioButton g_female;
    private javax.swing.JRadioButton g_male;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_nameWarning;
    private javax.swing.JLabel lbl_tcWarn;
    private javax.swing.JLabel lbl_warn;
    private javax.swing.JTextField name_txt;
    private javax.swing.JProgressBar pass_bar;
    private javax.swing.JPasswordField pass_txt;
    private javax.swing.JFormattedTextField phone_txt;
    private javax.swing.JPanel pnl_udatePatient;
    private javax.swing.JTextField surname_txt;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JFormattedTextField txt_tcno;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
